spring.application.name=NeoWaves
spring.datasource.url=jdbc:postgresql://localhost:5432/waves_db
server.port=8081
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ????????? ????????????? ?? ????? data.sql
spring.sql.init.mode=always

# ????????? data.sql ?????? ????? ????, ??? Hibernate ??????? ???????
spring.jpa.defer-datasource-initialization=true


