spring.application.name=NeoWaves
spring.datasource.url=jdbc:postgresql://localhost:5432/waves_db
server.port=8081
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=false


