spring.application.name=NeoWaves
server.port=8081

# ?????????? ???? ? ????? ????????????, ????? ?? ???? ??????? ? ??????? ? .exe
spring.datasource.url=jdbc:h2:file:~/waves_db;MODE=PostgreSQL;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ????????? Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=true

# ???????? ????????????? (????? ????? ??????????? ?? data.sql)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ???? (????? ???????? ??? ????????)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
